Tensor = smart box of numbers


In [1]:
import torch 
print(torch.__version__)

2.10.0+cpu


In [ ]:
x = torch.tensor([1,2,3,4,5]) #1d tensor
print(x)

tensor([1, 2, 3, 4, 5])


In [4]:
y = torch.tensor([[1,2],[3,4]]) #2d tensor ( matrix )
print(y)

tensor([[1, 2],
        [3, 4]])


In [7]:
torch.zeros(3,2) # rows and coulmns
torch.ones(3,2)  #ones
torch.rand(3,2) #random numbers

tensor([[0.6556, 0.8217],
        [0.0850, 0.5789],
        [0.6862, 0.3160]])

TENSOR SHAPES

In [ ]:
z = torch.tensor([[1,2,3],[4,5,6]])  
print(z.shape)   # rows then coulmns


torch.Size([2, 3])


In [ ]:
d_2 = torch.tensor([[1,2,3],[4,5,6]])
print(d_2[0,0]) # accessing by rows and coulmns
print(d_2[0,1]) # accessing by rows and coulmns
print(d_2[0,2]) # accessing by rows and coulmns
print(d_2[1,0]) # accessing by rows and coulmns
print(d_2[1,1]) # row then column

tensor(1)
tensor(2)
tensor(3)
tensor(4)
tensor(5)


OPERATIONS

In [17]:
x = torch.tensor([1,2,3])
y = torch.tensor([4,5,6])

print(x+y)
print(x*y)
print(x[0]+y[1])
print(x*2)

tensor([5, 7, 9])
tensor([ 4, 10, 18])
tensor(6)
tensor([2, 4, 6])


TENSOR FROM NUMPY


In [19]:
import numpy as np

arr = np.array([1,2,3])
t = torch.from_numpy(arr)

print(t)
print(type(t))

tensor([1, 2, 3])
<class 'torch.Tensor'>


Linear Regression

In [ ]:
x = torch.tensor([1.0,2.0,3.0])
y = torch.tensor([4.0,5.0,6.0])

#wrong guessing 
w = torch.tensor(0.0)
s = torch.tensor(0.0)

#step-4
y_pred = w * x + s

loss = ((y_pred - y) ** 2).mean()   #used square for positive outcome and mean to arrange bigger values 

print("Predicted Values :",y_pred)
print("Actual Values :",y)
print("Losses:",loss)

Predicted Values : tensor([0., 0., 0.])
Losses: tensor(25.6667)
